- platform: workday
  name: workday next day
  country: DE
  province: NW
  days_offset: 1

- platform: workday
  name: workday this day
  country: DE
  province: NW

- platform: template
  sensors:
    bathroom_window_manualy:
      friendly_name: "Badezimmer Fenster"
      device_class: window
      entity_id: sensor.bathroom_window_access_control
      value_template: >-
        {{ is_state('sensor.bathroom_window_access_control', '22') }}
    bedroom_door_manualy:
      friendly_name: "Schalfzimmer Tür"
      device_class: window
      entity_id: sensor.bedroom_door_access_control
      value_template: >-
        {{ is_state('sensor.bedroom_door_access_control', '22') }}
    bathroom_door_manualy:
      friendly_name: "Badezimmer Tür"
      device_class: window
      entity_id: sensor.bathroom_door_access_control
      value_template: >-
        {{ is_state('sensor.bathroom_door_access_control', '22') }}

- platform: ping
  host: 192.168.1.36
  name: Ping Nintendo Switch
  count: 2
  scan_interval: 10
- platform: ping
  host: 192.168.1.32
  name: Ping Xbox One X
  count: 2
  scan_interval: 10
- platform: ping
  host: 192.168.1.33
  name: Ping Xbox Series X
  count: 2
  scan_interval: 10
- platform: ping
  host: 192.168.1.21
  name: Ping Wohnzimmer TV
  count: 2
  scan_interval: 10
- platform: ping
  host: 192.168.1.38
  name: Macbook Privat
  count: 2
  scan_interval: 10
- platform: ping
  host: 192.168.1.39
  name: Macbook Arbeit
  count: 2
  scan_interval: 10
- platform: ping
  host: 192.168.1.34
  name: Fire TV Stick Schlafzimmer
  count: 2
  scan_interval: 10
- platform: ping
  host: 192.168.1.40
  name: Fire TV Stick 4k Wohnzimmer
  count: 2
  scan_interval: 10
# - platform: ping
#   host: 192.168.1.39
#   name: Fire TV Stick Wohnzimmer
#   count: 2
#   scan_interval: 10