- platform: wake_on_lan
  mac: "F8-32-E4-6F-07-D6"
  name: SkyNAS
  host: 192.168.1.3
  turn_off:
    service: shell_command.skynas_off

- platform: mqtt
  name: Christians Server
  state_topic: "home/server_main/switch1"
  command_topic: "home/server_main/switch1"
  retain: true
- platform: mqtt
  name: Backup Server Filme
  state_topic: "home/server_filme/switch1"
  command_topic: "home/server_filme/switch1"
  retain: true
- platform: mqtt
  name: Backup Server Serien
  state_topic: "home/server_serien/switch1"
  command_topic: "home/server_serien/switch1"
  retain: true

- platform: broadlink
  mac: '34:EA:34:58:BA:89'
  switches:
    btv:
      friendly_name: "Broadlink_Samsung TV Power"
      command_on: ''
      command_off: ''
    candle_small_power:
      friendly_name: "Teelichter Power"
      command_on: 'JgBYAAABK5YVERMSFBITEhQSExISFBITEzcTNxM3FDYUNhQ2FDYVNRURFBEVERQRFREUEhQ2FBEVNRU1FTUVNhQ2FDUVERU1FAAFFwABL0kSAAxSAAEuSRMADQU=='
      command_off: 'JgBYAAABLZQTEhMTExITExMSExMTEhMTEzcTNxM3EzcTNxM3EzcTNhQ2FBITEhQ2EzcTExMSExMTEhM3EzcTExMSEzcTNxM3EwAFIQABLUkTAAxeAAEtSRMADQU=='
    candle_small_plus:
      friendly_name: "Teelichter Helligkeit"
      command_on: 'JgBYAAABLpQUERQSExIUEhMTExITExMSEzYUNxM3EzcTNxM3EzcTNxMSExMTNxMSExMTEhM3ExMTNxM2FBITNxM3EzcTEhQ2FAAFIAABLUkTAAxcAAEvSRMADQU=='
      command_off: 'JgBYAAABLZMVERQSFBEUEhQRFBEVERQRFTUVNRU1FTUVNBY1FTUVNRURFDYUNhQRFDYUEhMSFBITNxMSExMTNxMSEzcTNxM3EwAFIgABLUkTAAxeAAEuSBQADQU=='
    candle_small_pulse_slow:
      friendly_name: "Teelichter Langsam Flackern"
      command_on: 'JgBYAAABLJUTExITExMSExMTEhMTExIUEjgSOBI3EzgSNxM3EzcUNhQ2FDYVERQRFREUERU1FREVEBURFDYVNRU1FDYUERU1FQAFHAABK0sWAAxRAAEtSxUADQU=='
      command_off: ''
    candle_small_pulse_fast:
      friendly_name: "Teelichter Schnell Flackern"
      command_on: 'JgBYAAABL5QVEBURFRAVERURFRAVERUQFTUVNRU1FTUVNRU1FTUVNRU1FREUNhQ2FBEVERQRFREUERU1FREUERU1FTUVNRU1FQAFHgABLEsSAAxZAAEuSxUADQU=='
      command_off: ''
    beamer_power_off:
      command_on: 'JgDYAAABKZIVNhQ2FREUEBURFBEVEBU1FDYUEhQ2ExIVNRQSFDYUERU1ExIVERUQFTUTEhURFDYVEBU1EzgUNhUQFTUVNRQSFQAFQAABK5EVNRQ2FREUERUQFRAVEBU2FDYUERU1FBIUNhQRFTUVEBU2FBEVEBUQFTYUERUQFTUUERU2FDYUNhQRFTUVNhQRFQAFQAABKpIVNRQ2FBIUERUQFRAVEBU2FDYUERU1FBIUNhQRFTUUERU2FBEVEBUQFTYUERUQFTUVEBU2FDYUNhQRFTYUNRYQFQANBQ=='
      command_off: 'JgDYAAABKZIVNhQ2FREUEBURFBEVEBU1FDYUEhQ2ExIVNRQSFDYUERU1ExIVERUQFTUTEhURFDYVEBU1EzgUNhUQFTUVNRQSFQAFQAABK5EVNRQ2FREUERUQFRAVEBU2FDYUERU1FBIUNhQRFTUVEBU2FBEVEBUQFTYUERUQFTUUERU2FDYUNhQRFTUVNhQRFQAFQAABKpIVNRQ2FBIUERUQFRAVEBU2FDYUERU1FBIUNhQRFTUUERU2FBEVEBUQFTYUERUQFTUVEBU2FDYUNhQRFTYUNRYQFQANBQ=='
    candle_big_power:
      friendly_name: 'Kerzen Gross'
      command_on: 'JgBgAAABHJMQExETEhIRExETERMRExETETcROBA3EjcRNxE3EzUROBA4EhIRExETERMRExETERMQFBE3ETcSNhI3EDgRNxE4EAAFCgABHUkSAAwjAAEdSREADBwAARxJEwANBQAAAAAAAAAA=='
      command_off: 'JgBYAAABHZIRExQQEhIRExQQFBARExETFDQSNxE3ETcSNxA4FDQUNRA4ERMRExE3ERMRExITEBMSEhI3EzURExE4EDgRNhI4EAAFCwABHkkRAAwgAAEdSREADQU=='
    samsung_tv_hdmi_1:
      friendly_name: 'Samsung Wohnzimmer HDMI 1'
      command_on: 'JgBGAJOSEjcUMxUzFQ4UDhEREREUDxMzETcSNxMQEw4UDhEREhAUMxUOERERNxQPEzMRNxI3ExATMxUzEhEUMxIRExATDhQADQUAAA=='
      command_off: 'JgBGAJOSEjcUMxUzFQ4UDhEREREUDxMzETcSNxMQEw4UDhEREhAUMxUOERERNxQPEzMRNxI3ExATMxUzEhEUMxIRExATDhQADQUAAA=='
    samsung_tv_hdmi_2:
      friendly_name: 'Samsung Wohnzimmer HDMI 2'
      command_on: 'JgBGAJOUETkRORA6ERQQFRAVERQRFBA6ETkROhAVDxYQFQ8WEBUQFQ87EDoRORA6DzsQFRA6DzsPFhAVDxYQFRAVEDoQFRAADQUAAA=='
      command_off: 'JgBGAJOUETkRORA6ERQQFRAVERQRFBA6ETkROhAVDxYQFQ8WEBUQFQ87EDoRORA6DzsQFRA6DzsPFhAVDxYQFRAVEDoQFRAADQUAAA=='
    samsung_tv_hdmi_3:
      friendly_name: 'Samsung Wohnzimmer HDMI 3'
      command_on: 'JgBGAJOUEDoRORE5ERQRFRAUERQRFBE5EDsQOhAVEBUPFg8WDxYPFhA6EBUPFg8WEBUROQ87EDoQFQ87EDoQOhA6EBUPFhAADQUAAA=='
      command_off: 'JgBGAJOUEDoRORE5ERQRFRAUERQRFBE5EDsQOhAVEBUPFg8WDxYPFhA6EBUPFg8WEBUROQ87EDoQFQ87EDoQOhA6EBUPFhAADQUAAA=='
    samsung_tv_hdmi_4:
      friendly_name: 'Samsung Wohnzimmer HDMI 4'
      command_on: 'JgBGAJOVETgRORE6DxYQFQ8WDxYPFhA6EDoQOhAVDxYQFQ8WDxYPOw8WEDoQFRAVDxYPOxA6EBUQOhAVEDoQOhA6EBUPFhAADQUAAA=='
      command_off: 'JgBGAJOVETgRORE6DxYQFQ8WDxYPFhA6EDoQOhAVDxYQFQ8WDxYPOw8WEDoQFRAVDxYPOxA6EBUQOhAVEDoQOhA6EBUPFhAADQUAAA=='
    samsung_tv_exit:
      friendly_name: 'Samsung Wohnzimmer Exit'
      command_on: 'JgCMAJOTEjcTNxI3EhMSEhITEhMRExI3EjcSOBISEhMSExETEhMSNxITEjcSNxITEjcSExETEhMSNxITEhISNxITEjcSOBEABfuTlBI3EjcSOBETEhMSEhITEhMROBI3EjcSExITERMSExISEjgRExI3EjcSExI3EhMSExISEjgRExITEjcSExE4EjcSAA0FAAAAAAAAAAAAAAAA=='
      command_off: 'JgCMAJOTEjcTNxI3EhMSEhITEhMRExI3EjcSOBISEhMSExETEhMSNxITEjcSNxITEjcSExETEhMSNxITEhISNxITEjcSOBEABfuTlBI3EjcSOBETEhMSEhITEhMROBI3EjcSExITERMSExISEjgRExI3EjcSExI3EhMSExISEjgRExITEjcSExE4EjcSAA0FAAAAAAAAAAAAAAAA=='
    samsung_tv_back:
      friendly_name: 'Samsung Wohnzimmer Back'
      command_on: 'JgBGAJKWDzsQOhA6EBUPFhAVEBUQFQ87EDoSOBAVEBUPFhITEBUQFREUERQQOhA6EBUQOhAVEDoQOhA6ERQQFRE5EBUPOxEADQUAAA=='
      command_off: 'JgBGAJKWDzsQOhA6EBUPFhAVEBUQFQ87EDoSOBAVEBUPFhITEBUQFREUERQQOhA6EBUQOhAVEDoQOhA6ERQQFRE5EBUPOxEADQUAAA=='
    samsung_tv_power_on:
      friendly_name: 'Samsung Wohnzimmer An'
      command_on: 'JgBGAJKVETkRORA6ERQRFBEUERQRFBE5ETkQOhAVEBUQFREUEBUQOhEUERQRORE5EBURFBA6EBUQOhE5EBUQFRA6EDoRFBEADQUAAA=='
      command_off: ''


  #########More IR Code fpr Samsung TV -> https://github.com/yahat/broadlink_mini_homeassistant_ir_codes_samsung_tv
